export const CHANGE_NAME_FIELD = 'CHANGE_NAME_FIELD';
export const CHANGE_VALUE_FIELD = 'CHANGE_VALUE_FIELD';
export const CHANGE_RECURRENCE_FIELD = 'CHANGE_RECURRENCE_FIELD';
export const CHANGE_OCCUPANTION_FIELD = 'CHANGE_OCCUPANTION_FIELD';

export const SET_MEMBERS_ARRAY = 'SET_MEMBERS_ARRAY';

export const SET_TABLE_TOP = 'SET_TABLE_TOP';
export const SET_TABLE_BOTTOM = 'SET_TABLE_BOTTOM';

export const SET_VALUETYPE = 'SET_VALUETYPE';
export const SET_VALUETYPE_BOTTOM = 'SET_VALUETYPE_BOTTOM';