export const CHANGE_NAME_FIELD = 'CHANGE_NAME_FIELD';
export const CHANGE_VALUE_FIELD = 'CHANGE_VALUE_FIELD';
export const CHANGE_RECURRENCE_FIELD = 'CHANGE_RECURRENCE_FIELD';
export const CHANGE_OCCUPANTION_FIELD = 'CHANGE_OCCUPANTION_FIELD';

export const SET_MEMBERS_ARRAY = 'SET_MEMBERS_ARRAY';

export const SET_TABLE = 'SET_TABLE';

export const SET_VALUETYPE = 'SET_VALUETYPE';

export const SET_TABLETYPE_SUMMARY = 'SET_TABLETYPE_SUMMARY';
export const SET_TABLETYPE_INCOMINGS = 'SET_TABLETYPE_INCOMINGS';
export const SET_TABLETYPE_EXPENSES = 'SET_TABLETYPE_EXPENSES';

export const SET_RECURRENCE = 'SET_RECURRENCE';
export const SET_OCCUPANT = 'SET_OCCUPANT';